### ISSUE TITLE
GoPro Hero 4 Black not functioning

### ISSUE THREAD

**Issue by fusi0nfire** [joshvillbrandt/GoProController#5] opened 2015-02-11 19:14 UTC
The Hero 4 Black does not communicate status while sleeping.  It does not power on by command.  It will report when turned on, and will receive record and sleep commands.  The rest seem to be ignored.

**Comment by etchicago** [comment] 2015-02-11 19:33
Josh

I have been following your activities as you seem to be closest to a need I have for use in Air Search and Rescue. 

I am looking to have three (min) to four cameras, controlled by a tablet that can be set to take periodic pictures and confirm function / activity back to the tablet.  Clearly I would need to explain more.  Would you be open to the discussion and looking to build a prototype.  

We also need GPS data imbedded into the metadata of the individual pictures.

Thoughs, interested?

Eric Templeton, Commandant
National Emergency Services Academy - Aircrew School
(630) 261-5873
etempleton@nesa.cap.gov <mailto:etempleton@nesa.cap.gov>

www.nesa.cap.gov <http://www.nesa.cap.gov/> 



-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Eric Templeton
etchicago@yahoo.com <mailto:etchicago@yahoo.com>
+1 (630) 261-5873 (mobile)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

**Comment by joshvillbrandt** [comment] 2015-02-14 05:15
Hey Eric,

Thanks for reaching out to me, however I am not in a position to take on
additional work at the moment.

Best of luck coming up with a solution!

Josh Villbrandt
(717) 891-9077
http://javconcepts.com/

Avionics Systems Integration Engineer, Space Exploration Technologies
MS Computer Science (Intelligent Robotics), University of Southern
California '12
BS Aerospace Engineering, University of Southern California '11

**Comment by joshvillbrandt** [comment] 2015-02-14 05:23
@fusi0nfire - I have also had some difficulties with the GoPro HERO 4. It has been a month or two since I last tried a HERO 4, but I think I saw the exact same behavior. It seems that GoPro has changed the API here.

I have also seen the HERO 4s drop out of wifi communication completely within about 30 minutes when HERO 3 cameras will continue to last for days. Issue #4 has more discussion on that for anyone stumbling across this ticket.

Note that I believe GoPro has added a secondary API with the HERO 4 cameras and my library does not yet take that into account. There is likely away to turn the camera on when sleeping, but I haven't sought it out yet.

**Comment by joshvillbrandt** [comment] 2015-02-14 05:29
FYI, this is a duplicate of https://github.com/joshvillbrandt/goprohero/issues/3, so I'm closing this issue.

**Closed by joshvillbrandt** 2015-02-14 05:29 UTC

**Comment by etchicago** [comment] 2015-02-14 15:28
HI Josh 

Thanks for getting back to me, anyone you know who might enjoy working on this?

Eric

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Eric Templeton
etchicago@yahoo.com <mailto:etchicago@yahoo.com>
+1 (630) 261-5873 (mobile)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
